export const departmentsContent = {
  headline: 'Every department. One platform.',
  subheadline: 'AI Employees embedded across your entire organization.',
  departments: [
    {
      id: 'finance',
      name: 'Finance',
      icon: 'TrendingUp',
      color: '#6D8BFF',
      employee: 'Aria — Finance AI',
      tasks: ['Invoice processing', 'Budget approvals', 'Financial reporting', 'Expense auditing'],
      description: 'Automates AP/AR workflows, reconciliation, and real-time financial analytics.',
      metric: { value: '92%', label: 'faster approvals' },
    },
    {
      id: 'hr',
      name: 'Human Resources',
      icon: 'Users',
      color: '#5AE7D2',
      employee: 'Max — HR AI',
      tasks: ['Onboarding automation', 'Policy Q&A', 'Leave management', 'Performance tracking'],
      description: 'Handles employee lifecycle from onboarding to offboarding with zero friction.',
      metric: { value: '80%', label: 'HR tickets resolved' },
    },
    {
      id: 'sales',
      name: 'Sales',
      icon: 'BarChart3',
      color: '#6D8BFF',
      employee: 'Nova — Sales AI',
      tasks: ['Lead qualification', 'CRM updates', 'Proposal generation', 'Follow-up sequences'],
      description: 'Qualifies leads, drafts proposals, and keeps your CRM spotless automatically.',
      metric: { value: '3x', label: 'pipeline velocity' },
    },
    {
      id: 'engineering',
      name: 'Engineering',
      icon: 'Code2',
      color: '#5AE7D2',
      employee: 'Koda — Dev AI',
      tasks: ['Code reviews', 'Bug triage', 'Documentation', 'Deploy pipelines'],
      description: 'Accelerates engineering cycles with automated reviews, docs, and incident response.',
      metric: { value: '60%', label: 'review time saved' },
    },
    {
      id: 'legal',
      name: 'Legal',
      icon: 'Scale',
      color: '#6D8BFF',
      employee: 'Lex — Legal AI',
      tasks: ['Contract review', 'Compliance checks', 'NDA drafting', 'Risk assessment'],
      description: 'Reviews contracts, flags risks, and drafts standard agreements in minutes.',
      metric: { value: '75%', label: 'faster contract review' },
    },
    {
      id: 'support',
      name: 'Customer Support',
      icon: 'MessageSquare',
      color: '#5AE7D2',
      employee: 'Echo — Support AI',
      tasks: ['Ticket resolution', 'Escalation routing', 'Knowledge base', 'SLA monitoring'],
      description: 'Resolves tickets instantly, learns from every interaction, escalates intelligently.',
      metric: { value: '98%', label: 'CSAT score' },
    },
  ],
};
