export const workflowContent = {
  eyebrow: 'Intelligent Workflow Engine',
  headline: 'From signal to action in seconds.',
  subheadline: 'Watch how an AI Employee handles a real business process — end to end, without human intervention.',
  steps: [
    {
      id: 'receive',
      icon: 'Mail',
      label: 'Email Received',
      description: 'Invoice from vendor lands in inbox',
      detail: 'vendor@acme.com → finance@orbiant.ai',
      color: '#6D8BFF',
    },
    {
      id: 'read',
      icon: 'Brain',
      label: 'AI Reads & Parses',
      description: 'Extracts vendor, amount, PO number',
      detail: '$24,500 · PO-2847 · Net 30',
      color: '#7A9AFF',
    },
    {
      id: 'verify',
      icon: 'ShieldCheck',
      label: 'Verification',
      description: 'Cross-checks against PO in ERP',
      detail: 'PO matched · Budget available',
      color: '#5AE7D2',
    },
    {
      id: 'approval',
      icon: 'CheckSquare',
      label: 'Smart Approval',
      description: 'Routes to approver based on amount',
      detail: 'Sarah Chen → approved in 4 min',
      color: '#4DD8C4',
    },
    {
      id: 'erp',
      icon: 'Database',
      label: 'ERP Updated',
      description: 'Payment scheduled, GL coded',
      detail: 'SAP S/4HANA · Account 6200',
      color: '#6D8BFF',
    },
    {
      id: 'notify',
      icon: 'Bell',
      label: 'Notification Sent',
      description: 'Vendor notified, team updated',
      detail: 'Payment scheduled: 2026-07-22',
      color: '#5AE7D2',
    },
    {
      id: 'done',
      icon: 'Sparkles',
      label: 'Audit Trail',
      description: 'Full log stored, compliant',
      detail: '100% audit trail · SOC2 compliant',
      color: '#6D8BFF',
    },
  ],
};
